---
abstract: 'Perl extension for alternative splicing analysis'
author:
  - 'Michael T. Wolfinger <michael@wolfinger.eu>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bio-ViennaNGS-SpliceJunc
no_index:
  directory:
    - t
    - inc
requires:
  Bio::ViennaNGS: '0'
  Carp: '0'
  Data::Dumper: '0'
  IPC::Cmd: '0'
  Path::Class: '0'
version: v0.3.0
